using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Windows.Controls;
using System.Windows;
using System.Windows.Controls.Primitives;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using IT;

namespace IT.WPF
{
	public class DataGridBehaviour
	{
		#region ScrollToView

		//private static SelectedCellsChangedEventHandler _scrollToViewEventHandler = new SelectedCellsChangedEventHandler(OnScrollToView);
		private static void OnScrollToView(object sender, SelectedCellsChangedEventArgs e)
		{
			if (sender is DataGrid)
			{
				DataGrid d = (DataGrid)sender;
				if (d.SelectedItem != null)
				{
					d.UpdateLayout();
					d.ScrollIntoView(d.SelectedItem);
					if (GetSetKeyboardFocusOnScrollToView(d))
					{
						#region settign keyboard focus to a first cell on the row
						//TODO check if it is a normal solution
						DataGridRow row = (DataGridRow)d.ItemContainerGenerator.ContainerFromIndex(d.SelectedIndex);
						if (row != null)
						{
							DataGridCellsPresenter dgCP = row.GetVisualChildren<DataGridCellsPresenter>().FirstOrDefault();

							if (dgCP == null)
							{
								d.ScrollIntoView(row, d.Columns[0]);
								dgCP = row.GetVisualChildren<DataGridCellsPresenter>().FirstOrDefault();
							}

							if (dgCP != null)
							{
								DataGridCell cell = (DataGridCell)dgCP.ItemContainerGenerator.ContainerFromIndex(0);
								if (cell != null)
								{
									cell.Focus();
								}
							}
						}
						#endregion // settign keyboard focus to a first cell on the row
					}
				}
			}
		}

		public static readonly DependencyProperty ScrollToViewProperty =
			DependencyProperty.RegisterAttached("ScrollToView",
					typeof(bool),
					typeof(DataGridBehaviour),
					new FrameworkPropertyMetadata(false,
						(d, e) =>
						{
							//DependencyObject d, DependencyPropertyChangedEventArgs e
							var u = (System.Windows.Controls.DataGrid)d;
							if ((bool)e.OldValue && !(bool)e.NewValue)
							{
								// remove handlers
								u.SelectedCellsChanged -= OnScrollToView;// _scrollToViewEventHandler;
							}

							if (!(bool)e.OldValue && (bool)e.NewValue)
							{
								// add handlers
								u.SelectedCellsChanged += OnScrollToView;// _scrollToViewEventHandler;
							}
						}));

		public static bool GetScrollToView(DependencyObject element)
		{
			return (bool)element.GetValue(ScrollToViewProperty);
		}

		public static void SetScrollToView(DependencyObject element, bool value)
		{
			element.SetValue(ScrollToViewProperty, value);
		}

		#endregion

		public static readonly DependencyProperty SetKeyboardFocusOnScrollToViewProperty =
			DependencyProperty.RegisterAttached("SetKeyboardFocusOnScrollToView", typeof(bool), typeof(DataGridBehaviour));

		public static bool GetSetKeyboardFocusOnScrollToView(DependencyObject element)
		{
			return (bool)element.GetValue(SetKeyboardFocusOnScrollToViewProperty);
		}

		public static void SetSetKeyboardFocusOnScrollToView(DependencyObject element, bool value)
		{
			element.SetValue(SetKeyboardFocusOnScrollToViewProperty, value);
		}

		#region FilteredColumns (on Autogenerate)

		/// <summary>
		/// Фильтрация столбцов во атрибуту BrowsableAttribute, 
		/// для EnumDataTypeAttribute создает DataGridComboBoxColumn, 
		/// по атрибуту EditableAttribute определяется свойство IsReadOnly
		/// вытаскивание имени столбца из атрибутов DisplayAttribute и DisplayNameAttribute
		/// </summary>
		public static readonly DependencyProperty FilteredColumnsProperty =
			DependencyProperty.RegisterAttached("FilteredColumns", typeof(bool), typeof(DataGridBehaviour), new PropertyMetadata(false, FilteredColumnsChangedCallback));

		public static bool GetFilteredColumns(DependencyObject element)
		{
			return (bool)element.GetValue(FilteredColumnsProperty);
		}

		public static void SetFilteredColumns(DependencyObject element, bool value)
		{
			element.SetValue(FilteredColumnsProperty, value);
		}

		static void FilteredColumnsChangedCallback(DependencyObject d, DependencyPropertyChangedEventArgs e)
		{
			var dg = d as DataGrid;
			if ((bool)e.NewValue)
			{
				dg.AutoGeneratingColumn += dg_AutoGeneratingColumn;
				dg.AutoGeneratedColumns += Dg_AutoGeneratedColumns;
			}
			else
			{
				dg.AutoGeneratingColumn -= dg_AutoGeneratingColumn;
				dg.AutoGeneratedColumns -= Dg_AutoGeneratedColumns;
			}
		}

		private static void Dg_AutoGeneratedColumns(object sender, EventArgs e)
		{

		}

		static void dg_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
		{
			var pd = (PropertyDescriptor)e.PropertyDescriptor;
			if (pd.GetAttributeValue<BrowsableAttribute, bool>(a => a.Browsable, true))
			{
				var txtCol = e.Column as DataGridTextColumn;

				var enumType = pd.GetAttributeValue<EnumDataTypeAttribute, Type>(a => a.EnumType, null);
				if (enumType != null && txtCol != null)
				{
					var cbCol = e.Column as DataGridComboBoxColumn;
					if (cbCol == null)
					{
						cbCol = new DataGridComboBoxColumn();
						var intType = Enum.GetUnderlyingType(enumType);
						cbCol.ItemsSource = Enum.GetValues(enumType)
							.Cast<Enum>()
							.ToDictionary(i => Convert.ChangeType(i, intType), i => i.ToString());
						cbCol.SelectedValueBinding = txtCol.Binding;
						cbCol.SelectedValuePath = "Key";
						cbCol.DisplayMemberPath = "Value";
					}
					e.Column = cbCol;
				}

				e.Column.IsReadOnly = !pd.GetAttributeValue<EditableAttribute, bool>(a => a.AllowEdit, true);
				var attr = pd.Attributes.OfType<DisplayAttribute>().FirstOrDefault();
				if (attr != null)
				{
					e.Column.Header = attr.ShortName ?? attr.Name ?? e.PropertyName;
				}
				else
				{
					e.Column.Header = pd.GetAttributeValueStr<DisplayNameAttribute>(a => a.DisplayName) ?? e.PropertyName;
				}
			}
			else
			{
				e.Cancel = true;
			}
		}

		#endregion

		#region Columns

		public static readonly DependencyProperty ColumnsProperty =
		DependencyProperty.RegisterAttached("Columns",
											typeof(IEnumerable<DataGridColumn>),
											typeof(DataGridBehaviour),
											new UIPropertyMetadata(null, ColumnsPropertyChanged));

		public static ObservableCollection<DataGridColumn> GetColumns(DependencyObject element)
		{
			return (ObservableCollection<DataGridColumn>)element.GetValue(ColumnsProperty);
		}

		public static void SetColumns(DependencyObject element, ObservableCollection<DataGridColumn> value)
		{
			element.SetValue(ColumnsProperty, value);
		}

		private static void ColumnsPropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e)
		{
			var dataGrid = (DataGrid)source;
			var columns = (IEnumerable<DataGridColumn>)e.NewValue;

			if (e.OldValue != null)
			{
				foreach (DataGridColumn column in (IEnumerable<DataGridColumn>)e.OldValue)
				{
					dataGrid.Columns.Remove(column);
				}
			}

			if (columns != null)
			{
				foreach (DataGridColumn column in columns)
				{
					dataGrid.Columns.Add(column);
				}

				//columns.CollectionChanged += ColumnsChanged;
				//Localization.Localization.UpdateLocaleAtDataGridColumns(dataGrid);
			}
		}

		//static void ColumnsChanged(object sender, NotifyCollectionChangedEventArgs e2)
		//{
		//		if (e2.Action == NotifyCollectionChangedAction.Reset) {
		//			dataGrid.Columns.Clear();
		//			foreach (DataGridColumn column in e2.OldItems) {
		//				dataGrid.Columns.Remove(column);
		//			}
		//			foreach (DataGridColumn column in e2.NewItems) {
		//				dataGrid.Columns.Add(column);
		//			}
		//		} else if (e2.Action == NotifyCollectionChangedAction.Add) {
		//			foreach (DataGridColumn column in e2.NewItems) {
		//				dataGrid.Columns.Add(column);
		//			}
		//		} else if (e2.Action == NotifyCollectionChangedAction.Move) {
		//			dataGrid.Columns.Move(e2.OldStartingIndex, e2.NewStartingIndex);
		//		} else if (e2.Action == NotifyCollectionChangedAction.Remove) {
		//			foreach (DataGridColumn column in e2.OldItems) {
		//				dataGrid.Columns.Remove(column);
		//			}
		//		} else if (e2.Action == NotifyCollectionChangedAction.Replace) {
		//			dataGrid.Columns[e2.NewStartingIndex] = (DataGridColumn)e2.NewItems[0];
		//		}
		//		//Localization.Localization.UpdateLocaleAtDataGridColumns(dataGrid);

		//}

		#endregion

	}
}
